### ISSUE TITLE
Cliente se queda atascado

### ISSUE THREAD

**Issue by germanfr** [ggrupo/ataxx#4]
Cuando ejecutas el cliente se queda atascado al crear una nueva conexión _(línea 82)_. Creo que es porque no coge el hostname. Lo he probado con localhost y 127.0.0.1.

**Comment by galons01** [comment]
he corregido algunos errores, no consigo entender porque el cliente no acepta el "OK" del servidor.

**Comment by galons01** [comment]
10fe41b2730fffefe78d218462502f31371acd91 este es el ultimo commit

**Comment by germanfr** [comment]
Creo que era un problema de debug. Cierro.
